
# File scanning
###############

# directories to search
directories:
  - /home/cody/dev/python/aacme
#  - /home/cody/Downloads

# the file extensions to process
extensions:
  - mp4
  - avi
  - mpv
  - mkv




# ffmpgeg
#########

# set the new codec name and bitrate
audio_codec: aac
audio_bitrate: 320k

# add any extra encoding params to add on to the end of the command
extra_encode_params: '-strict experimental'

# max time to to allow for encoding before killing the process
encode_timeout_mins: 240




# logging
#########
logging:

   # define the available message formats
  formatters:
    # short messages for the screen
    short:
      format: '%(message)s'
    # long messages for the log file
    long:
      format: '%(asctime)s %(levelname)-8s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'


  # define the log handlers, we can optionally override the level that the handler will log
  handlers:

    # this logs to the screen
    console:
#      formatter: short
      formatter: long
      class: logging.StreamHandler
      stream: ext://sys.stdout

    # this logs to rotating log file
    file:
      formatter: long
      class : logging.handlers.RotatingFileHandler
      filename: aacme.log
      maxBytes: 1024
      backupCount: 3

  # connect the handlers and define the default log level
  root:
    level: DEBUG
    handlers: [console, file]

  # required version for python
  version: 1
