directories:
  - /home/cody/Downloads

extensions:
  - mp4
  - avi
  - mpv

logging:
  version: 1
  formatters:
    short:
      format: '%(message)s'
    long:
      format: '%(asctime)s %(levelname)-8s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
#      formatter: short
      formatter: long
      class: logging.StreamHandler
      stream: ext://sys.stdout
    file:
      formatter: long
      class : logging.handlers.RotatingFileHandler
      filename: aacme.log
      maxBytes: 1024
      backupCount: 3
  root:
    level: DEBUG
    handlers: [console, file]
